import type { WordCatalogEntry } from './spelling'

const entries = [
  ['ant', 5, 7, 1, ['animals']], ['apple', 5, 7, 1, ['food']], ['back', 5, 7, 1, ['core']],
  ['ball', 5, 7, 1, ['play']], ['bed', 5, 7, 1, ['home']], ['bell', 5, 7, 1, ['sound']],
  ['bird', 5, 7, 1, ['animals']], ['blue', 5, 7, 1, ['colors']], ['boat', 5, 7, 1, ['travel']],
  ['book', 5, 7, 1, ['school']], ['cake', 5, 7, 1, ['food']], ['cat', 5, 7, 1, ['animals']],
  ['chair', 5, 7, 1, ['home']], ['cloud', 5, 7, 1, ['weather']], ['coat', 5, 7, 1, ['clothes']],
  ['corn', 5, 7, 1, ['food']], ['dance', 5, 7, 1, ['play']], ['day', 5, 7, 1, ['time']],
  ['doll', 5, 7, 1, ['play']], ['door', 5, 7, 1, ['home']], ['drum', 5, 7, 1, ['music']],
  ['duck', 5, 7, 1, ['animals']], ['farm', 5, 7, 1, ['places']], ['fish', 5, 7, 1, ['animals']],
  ['frog', 5, 7, 1, ['animals']], ['game', 5, 7, 1, ['play']], ['gate', 5, 7, 1, ['home']],
  ['gift', 5, 7, 1, ['celebration']], ['glad', 5, 7, 1, ['feelings']], ['grape', 5, 7, 1, ['food']],
  ['green', 5, 7, 1, ['colors']], ['hand', 5, 7, 1, ['body']], ['hat', 5, 7, 1, ['clothes']],
  ['hill', 5, 7, 1, ['nature']], ['jump', 5, 7, 1, ['play']], ['kite', 5, 7, 1, ['play']],
  ['lamp', 5, 7, 1, ['home']], ['leaf', 5, 7, 1, ['nature']], ['light', 5, 7, 1, ['home']],
  ['milk', 5, 7, 1, ['food']], ['moon', 5, 7, 1, ['space']], ['nest', 5, 7, 1, ['animals']],
  ['park', 5, 7, 1, ['places']], ['pink', 5, 7, 1, ['colors']], ['plane', 5, 7, 1, ['travel']],
  ['plant', 5, 7, 1, ['nature']], ['rain', 5, 7, 1, ['weather']], ['ring', 5, 7, 1, ['objects']],
  ['robot', 5, 7, 1, ['play']], ['school', 5, 7, 1, ['school']], ['seed', 5, 7, 1, ['nature']],
  ['ship', 5, 7, 1, ['travel']], ['shoe', 5, 7, 1, ['clothes']], ['shop', 5, 7, 1, ['places']],
  ['sing', 5, 7, 1, ['music']], ['snow', 5, 7, 1, ['weather']], ['sock', 5, 7, 1, ['clothes']],
  ['star', 5, 7, 1, ['space']], ['stone', 5, 7, 1, ['nature']], ['sun', 5, 7, 1, ['space']],
  ['swing', 5, 7, 1, ['play']], ['table', 5, 7, 1, ['home']], ['tiger', 5, 7, 1, ['animals']],
  ['train', 5, 7, 1, ['travel']], ['tree', 5, 7, 1, ['nature']], ['water', 5, 7, 1, ['nature']],
  ['window', 5, 7, 1, ['home']], ['yellow', 5, 7, 1, ['colors']], ['zebra', 5, 7, 1, ['animals']],

  ['above', 7, 9, 2, ['position']], ['almost', 7, 9, 2, ['core']], ['animal', 7, 9, 2, ['animals']],
  ['basket', 7, 9, 2, ['objects']], ['beach', 7, 9, 2, ['places']], ['begin', 7, 9, 2, ['school']],
  ['blanket', 7, 9, 2, ['home']], ['branch', 7, 9, 2, ['nature']], ['bright', 7, 9, 2, ['describing']],
  ['bubble', 7, 9, 2, ['play']], ['candle', 7, 9, 2, ['home']], ['captain', 7, 9, 2, ['people']],
  ['castle', 7, 9, 2, ['places']], ['cereal', 7, 9, 2, ['food']], ['circle', 7, 9, 2, ['math']],
  ['climber', 7, 9, 2, ['people']], ['closet', 7, 9, 2, ['home']], ['corner', 7, 9, 2, ['position']],
  ['dragon', 7, 9, 2, ['magic']], ['dream', 7, 9, 2, ['feelings']], ['every', 7, 9, 2, ['core']],
  ['family', 7, 9, 2, ['people']], ['feather', 7, 9, 2, ['animals']], ['flower', 7, 9, 2, ['nature']],
  ['friend', 7, 9, 2, ['people']], ['garden', 7, 9, 2, ['nature']], ['giant', 7, 9, 2, ['describing']],
  ['glitter', 7, 9, 2, ['magic']], ['hammer', 7, 9, 2, ['objects']], ['happen', 7, 9, 2, ['core']],
  ['happy', 7, 9, 2, ['feelings']], ['hidden', 7, 9, 2, ['describing']], ['jacket', 7, 9, 2, ['clothes']],
  ['jungle', 7, 9, 2, ['places']], ['kitten', 7, 9, 2, ['animals']], ['ladder', 7, 9, 2, ['objects']],
  ['letter', 7, 9, 2, ['school']], ['magic', 7, 9, 2, ['magic']], ['market', 7, 9, 2, ['places']],
  ['middle', 7, 9, 2, ['position']], ['minute', 7, 9, 2, ['time']], ['napkin', 7, 9, 2, ['home']],
  ['ocean', 7, 9, 2, ['nature']], ['orange', 7, 9, 2, ['colors']], ['outside', 7, 9, 2, ['position']],
  ['paint', 7, 9, 2, ['art']], ['pillow', 7, 9, 2, ['home']], ['planet', 7, 9, 2, ['space']],
  ['pocket', 7, 9, 2, ['clothes']], ['pretty', 7, 9, 2, ['describing']], ['purple', 7, 9, 2, ['colors']],
  ['rabbit', 7, 9, 2, ['animals']], ['rainbow', 7, 9, 2, ['weather']], ['rocket', 7, 9, 2, ['space']],
  ['sailor', 7, 9, 2, ['people']], ['silver', 7, 9, 2, ['colors']], ['snowman', 7, 9, 2, ['weather']],
  ['spring', 7, 9, 2, ['time']], ['story', 7, 9, 2, ['school']], ['street', 7, 9, 2, ['places']],
  ['summer', 7, 9, 2, ['time']], ['teacher', 7, 9, 2, ['people']], ['thunder', 7, 9, 2, ['weather']],
  ['tunnel', 7, 9, 2, ['places']], ['winter', 7, 9, 2, ['time']], ['wonder', 7, 9, 2, ['feelings']],

  ['adventure', 9, 12, 3, ['stories']], ['answer', 9, 12, 3, ['school']], ['beautiful', 9, 12, 3, ['describing']],
  ['because', 9, 12, 3, ['core']], ['blanket', 9, 12, 3, ['home']], ['calendar', 9, 12, 3, ['time']],
  ['careful', 9, 12, 3, ['describing']], ['celebrate', 9, 12, 3, ['celebration']], ['century', 9, 12, 3, ['time']],
  ['chocolate', 9, 12, 3, ['food']], ['collect', 9, 12, 3, ['core']], ['compass', 9, 12, 3, ['objects']],
  ['crystal', 9, 12, 3, ['magic']], ['curious', 9, 12, 3, ['feelings']], ['daughter', 9, 12, 3, ['people']],
  ['discover', 9, 12, 3, ['core']], ['distant', 9, 12, 3, ['describing']], ['dragonfly', 9, 12, 3, ['animals']],
  ['electric', 9, 12, 3, ['science']], ['enough', 9, 12, 3, ['core']], ['feast', 9, 12, 3, ['celebration']],
  ['festival', 9, 12, 3, ['celebration']], ['fraction', 9, 12, 3, ['math']], ['galaxy', 9, 12, 3, ['space']],
  ['giggle', 9, 12, 3, ['feelings']], ['guardian', 9, 12, 3, ['people']], ['history', 9, 12, 3, ['school']],
  ['imagine', 9, 12, 3, ['stories']], ['journey', 9, 12, 3, ['travel']], ['library', 9, 12, 3, ['places']],
  ['measure', 9, 12, 3, ['math']], ['message', 9, 12, 3, ['communication']], ['mountain', 9, 12, 3, ['nature']],
  ['musician', 9, 12, 3, ['people']], ['mystery', 9, 12, 3, ['stories']], ['neighbor', 9, 12, 3, ['people']],
  ['orchard', 9, 12, 3, ['nature']], ['outline', 9, 12, 3, ['school']], ['pattern', 9, 12, 3, ['math']],
  ['penguin', 9, 12, 3, ['animals']], ['picture', 9, 12, 3, ['art']], ['pioneer', 9, 12, 3, ['history']],
  ['practice', 9, 12, 3, ['school']], ['protect', 9, 12, 3, ['core']], ['recess', 9, 12, 3, ['school']],
  ['remember', 9, 12, 3, ['core']], ['science', 9, 12, 3, ['school']], ['shadow', 9, 12, 3, ['nature']],
  ['special', 9, 12, 3, ['describing']], ['squirrel', 9, 12, 3, ['animals']], ['stretch', 9, 12, 3, ['body']],
  ['student', 9, 12, 3, ['people']], ['surprise', 9, 12, 3, ['feelings']], ['treasure', 9, 12, 3, ['stories']],
  ['triangle', 9, 12, 3, ['math']], ['umbrella', 9, 12, 3, ['weather']], ['unicorn', 9, 12, 3, ['magic']],
  ['vacation', 9, 12, 3, ['time']], ['whisper', 9, 12, 3, ['communication']], ['wizard', 9, 12, 3, ['magic']]
] as const

export const WORD_CATALOG: WordCatalogEntry[] = entries.map(([word, ageBandMin, ageBandMax, difficulty, tags]) => ({
  id: word,
  word,
  normalizedWord: word.toLowerCase(),
  ageBandMin,
  ageBandMax,
  difficulty,
  tags: [...tags]
}))
